<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью виджета информационной панели (Dashboard).
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Виджет "Версия системы"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Виджет <a href="<?= $url('index', 'module:gm.be.dashboard') ?>">информационной панели (дашборд)</a> отображает информацию о версии вашего веб-приложения.</p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('options') ?>">Настройка виджета "Версия системы"</a></li>
    </ul>
</article>