<?php
/**
 * Страница "Настройка виджета".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью виджета информационной панели (Dashboard).
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Настройка виджета "Версия системы"</h1>
    <p>Форму настроек виджета можно вызвать из панели инструментов виджета, нажав кнопку <b>"Настроить"</b>.</p>
    <h2>Поля формы</h2>

    <h3>Разделы</h3>
    <p>Версия системы имеет следующие разделы:</p>
    <ul class="g-help-list">
        <li><b>Веб-приложение.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Редакция.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Панель управления.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Фреймворк.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
    
    <h3>Пункты разделов</h3>
    <p>Разделы версии имеет следующие пункты:</p>
    <ul class="g-help-list">
        <li><b>Номер версии.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Дата выпуска.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Подробнее.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
</article>